services:
  backend:
    build: ./backend
    container_name: backend
    environment:
        - DATABASE_URL=postgresql://postgres:password@vehicle-db:5432/vehicles?schema=public
    ports:
        - "4000:4000"
    depends_on:
        - postgres
    networks:
        - default

  postgres:
    container_name: vehicle-db
    image: postgres:14-alpine
    environment:
    - POSTGRES_USER=${POSTGRES_SUPER_USER:-postgres}
    - POSTGRES_PASSWORD=${POSTGRES_SUPER_PASS:-password}
    - APP_DB_USER=${APP_DB_USER:-docker}
    - APP_DB_PASS=${APP_DB_PASS:-docker}
    - APP_DB_NAME=${APP_DB_NAME:-vehicles}
    volumes:
    - ./util/init_db.sh:/docker-entrypoint-initdb.d/docker-entrypoint.sh
    ports:
      - "5432:5432"
    networks:
    - default
    
  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - default

networks:
    default:
        name: vehicle-db
        driver: bridge